development:
  adapter: mysql2
  database: firstorcreate_development
  user: root
  password:

test:
  adapter: mysql2
  database: firstorcreate_test
  user: root
  password:

production:
  adapter: mysql2
  database: firstorcreate_production
  user: root
  password:
